name: ⚙️ Test

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: cat dns resolver
        run: |
          cat /etc/resolv.conf

      - name: update dns resolver
        run: |
          sudo sed -i '1i nameserver ${{ secrets.CUSTOM_DNS }}' /etc/resolv.conf 2>&1
          return 0

      - name: dig domain
        run: |
          dig github.com
          dig ${{ secrets.DOMAIN }}