name: ⚙️ K8s staging dispatch

on:
  repository_dispatch:
    types: [dispatch]
  workflow_dispatch:

jobs:
  deploy:
    name: K8sDeploy
    runs-on: arc-runner-set
    steps:
      - name: TestFail
        run: |
          echo "TestFail"
          exit 1

      - name: Warning
        if: ${{ failure() }}
        run: |
          curl https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=663ca579-e4fb-4ded-83d1-63b8f944aa42 \
            -H 'Content-Type: application/json' \
            -d '{
              "msgtype": "markdown",
              "markdown": {
                "content": "⚠️ K8s staging deploy failed, please check the logs.\n\n[Job Log]: https://github.com/dream-num/helm-chart-private/actions/runs/${{ github.run_id }}\n\n[Service]: ${{ github.event.client_payload.service }}"
              }
            }'